### ISSUE TITLE
move api-docs to this repo or link to backend-repo

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe.github.io#11]
Currently there is a [google-doc](https://docs.google.com/document/d/1RwN4BNhgMT5Nj9EWYRBWxIZck5iaawg9i_5FdAAderw/edit#heading=h.wp1a8ue6nwhv) explaining the api. 

This could be either handled directly in this repository or we could link it to a documentation in the [python-backend-workers repository](https://github.com/mapswipe/python-mapswipe-workers).

**Comment by Matthias-Schaub** [comment]
The documentation for the API is now at https://mapswipe-workers.readthedocs.io/en/stable/api.html
This page will be updated.
The website should link to the above url.
