### ISSUE TITLE
Add new project attributes to the import formular (import.html)

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/mapswipe.github.io#16]
- country
- purposeMessage/thankYouMessage
- exampleImage
- exampleMessage

exampleImage and exampleMessage are to give show the user what to map for. Those could be displayed either at the start of mapping a group and/or when clicking the information button (top right of the screen).

purposeMessage/thankYouMessage should describe the porpuse of a project very briefly (>140 chars) and will be shown to the user from time to time when finishing a group.

Please also see at the related issue of the backend: https://github.com/mapswipe/python-mapswipe-workers/issues/112

**Comment by Hagellach37** [comment]
should be moved to python-mapswipe-workers, has been addressed tgere akready
