### ISSUE TITLE
add the app to the F-droid repo

### ISSUE THREAD

**Issue by harry-wood** [mapswipe/mapswipe.github.io#2]
In relation to offering APK downloads ( https://github.com/mapswipe/mapswipe.github.io/commit/afcd39210e4a2cf2d556b6df2cd81ad923e771a6 ) it could be good to list the app on the [f-droid repo](https://f-droid.org).

As a user I quite like it just as a way of listing/finding open source apps, but also as an easy way to side-load apps on amazon devices, however...

I make this suggestion casually without really knowing what's involved, but I heard from @simonpoole (vespucci developer) that it's quite a hassle actually. In which case feel free to park this as a low priority idea.

**Comment by simonpoole** [comment]
The main issue with F-Droid is that it isn't simply a APK repo, they actually build the app with their own automated build system. This is OK to a certain point, but in the case of more complicated builds you tend to be depending on whoever setup the F-Droid side to do it correctly and have time when something goes wrong (which is btw why I would strongly suggest requiring a modified app version string for F-Droid or you will never notice build related issues that are specific to F-Droid),

The other problem is that they are fairly strict about only using open components which may or may not be an issue for you.

**Comment by PimDeWitte** [comment]
for now we're just going to stick with the apk. If you guys want to publish it on fdroid, feel free to, it's open source.

**Comment by harry-wood** [comment]
ooh yeah that does sound like a pain. Didn't realise f-droid builds the apps.

**Comment by jhenshall** [comment]
Any thoughts on this @laurentS ? 3 years old now.

**Comment by laurentS** [comment]
Yes, this was actually the [very first issue on mapswipe](https://github.com/mapswipe/mapswipe/issues/1). Can't be done, because mapswipe uses non-FLOSS libraries (firebase). See details on the ticket linked. I'll close this ticket here as well
