### ISSUE TITLE
Create a "Resources" site

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/mapswipe.github.io#20]
Create a Resources site with following sections
- Insights
    - Key numbers
        - Those numbers can be get from the [Mapswipe-Backend API](http://api.mapswipe.org/stats.json)
        - Open an issue at the [Mapswipe-Backend repository](https://github.com/mapswipe/python-mapswipe-workers) if more numbers are needed
    - Link to https://mapswipe.heigit.org/home/
- Training
    - https://mapswipe.heigit.org/tutorial/
    - https://wiki.openstreetmap.org/wiki/MapSwipe_guidance:_interpreting_satellite_imagery
- Mapswipeathon

Sub-ticket of: #17

**Comment by Matthias-Schaub** [comment]
The mapswipe osm wiki entry was updated recently. There should be a link to it as well.
https://wiki.openstreetmap.org/wiki/MapSwipe

**Comment by jhenshall** [comment]
This is covered by the new website. The content was instead split across the data and get involved pages. Still a ticket to add top level numbers #28
