### ISSUE TITLE
Use gulp to build the pages

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe.github.io#44]
Instead of manually updating the HTML pages, we should complete the setup initiated by Raphaelle when she rebuilt the site.

In short, it could look like this:
- edit the "source files" (all the `xxxx.shtml`) locally
- run `gulp build` to generate the actual HTML files under a subfolder ( say `docs`)
- push the result to github, which would then deploy the site from this subfolder

The structure for this is already in the [source-code](https://github.com/mapswipe/mapswipe.github.io/tree/source-code) branch, but we've diverged a little with the commits from 2019-10-10 in `master`.

To fix this:
- setup `npm` on your laptop (it's installed with node.js, for OSX, get the installer from https://nodejs.org/en/download/ (use the "LTS" version)
- in a terminal, you should be able to run `npm -v` and see something like `12.16.2`
- from there, go to the folder where you've cloned this git repo, and run `npm install` to install all the dependencies required to build the pages (the dependencies are installed in a folder called `node_modules`)
- once completed, you should be able to run `gulp develop` in the same folder. It will start a small local webserver, and show you the url (something like `http://localhost:8000`) to open to see the local version of the site (if its not working, try `node_modules/.bin/gulp develop`)
- change any of the `.Shtml` files, save, and the local site will rebuild itself automatically
- when you're happy with the changes, run `gulp build`, commit your changes to the `.shtml` and `docs/*.html` files (do not commit the `node_modules` folder), and push to github (and open a PR)

Once that workflow is working ok, I would suggest "backporting" the changes made in `master` to the `source-code` branch, pushing everything, and create a PR to make that workflow the normal one. We'll need to modify how github deploys the site at this point, but we can figure this out later.

**Comment by jhenshall** [comment]
Done and migrated to new 'website' repo.
